version: 2.1

jobs:
  tsurukame-prober:
    macos:
      xcode: 16.1.0
    steps:
      - checkout
      - run:
          command: swift run WaniKaniAPIProber "$TSURUKAME_PROBER_EMAIL" "$TSURUKAME_PROBER_PASSWORD"
          working_directory: ios/WaniKaniAPI

workflows:
  version: 2
  tsurukame-prober:
    jobs:
      - tsurukame-prober
